CREATE TABLE bbs.favorites ( id INT NOT NULL AUTO_INCREMENT , 
member_id INT NOT NULL , post_id INT NOT NULL , 
created_at TIMESTAMP NOT NULL , 
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
PRIMARY KEY (id));